### ISSUE TITLE
Hammer

### ISSUE THREAD

**Issue by Dennis-APPELS** [KayleighForeign/Terrabort#109]
As a player, I want to be able to wield a hammer, so that I can bludgeon the GATRs with something heavy to deal lots of damage

Definition of done:
- [ ] The design document depicts and details the functionality of the hammer
- [ ] The hammer can be selected as a weapon
- [ ] The hammer has a fleshed out move set for the player to attack with
- [ ] Using the hammer lets the player do a lot of damage in exchange for speed

Linked Stories:
