### ISSUE TITLE
Healing Item

### ISSUE THREAD

**Issue by Dennis-APPELS** [KayleighForeign/Terrabort#20]
As a player, I want to have a healing item that I can take on missions with me, so that I can heal back some of the damage from the GATR

Definition of done:
- [x] The healing item is locked in the player's item slots
- [x] There are is finite amount of them going into a mission
- [x] The healing item can be used to recover health
- [ ] Interrupting the animation before the health is gained does not consume the item
