### ISSUE TITLE
Recharge

### ISSUE THREAD

**Issue by Dennis-APPELS** [KayleighForeign/Terrabort#28]
As a player, I want to have an item that can replenish my stamina, so that I can play more aggressively for a moment

Definition of done:

- [ ] Recharge can be equipped in the preparation menu
- [ ] Recharge fully replenishes the stamina bar
- [ ] There is a cooldown
