### ISSUE TITLE
Overcharge

### ISSUE THREAD

**Issue by Dennis-APPELS** [KayleighForeign/Terrabort#36]
As a player, I want to have an item that can boost my attack power temporarily, so that I can land a really big hit when I get the opportunity

Definition of done:
- [x] Overcharge can be equipped in the preparation menu
- [ ] Overcharge causes the player's attacks to visibly do more damage
- [x] This effect lasts for a while
- [x] This effect has a cooldown
