### ISSUE TITLE
Pillar

### ISSUE THREAD

**Issue by Dennis-APPELS** [KayleighForeign/Terrabort#52]
As a player, I want to be able to summon a pillar from underneath me, so that I can reach higher parts of the GATR with my ground attacks

Definition of done:
- [ ] Pillar can be equipped in the preparation menu
- [ ] Using the item summons a pillar underneath the player and elevates them
- [ ] The pillar disappears after a few moments
- [ ] The pillar can be destroyed by GATRs
- [ ] This item has a cooldown
