### ISSUE TITLE
Dashing

### ISSUE THREAD

**Issue by Dennis-APPELS** [KayleighForeign/Terrabort#68]
As a player, I want to be able to dash into a direction with my shield, so that I can skillfully avoid damage from GATRs

Definition of done:
- [x] The player can dash into a direction
- [x] When dashing, the player gets a shield for a short moment
- [x] When dashing, the player cannot make any other inputs
- [x] Attacks coming from the direction the player is facing have their damage nullified
- [x] If the player continues to hold the dash button, they will start to sprint (Will change in future)
- [x] Both sprinting and dashing consume stamina
- [x] Dashes cannot be performed if the player is too low on stamina
