### ISSUE TITLE
Jumping

### ISSUE THREAD

**Issue by Dennis-APPELS** [KayleighForeign/Terrabort#81]
As a player, I want to be able to jump, so that I can reach higher parts of GATRs with my attacks

Definition of done:
- [ ] The player can jump
- [ ] The player can attack in the air
- [x] Jumping requires and takes stamina
